<?php

namespace app\controller;

use app\controller\common\LogHelper;
use app\BaseController;
use app\business\Curl;
use app\business\RequestUrl;
use think\facade\Lang;

class Base extends BaseController
{
    public static $user;

    public function initialize()
    {
        $this->user_info();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function user_info()
    {
        $token = $this->request->header('x-csrf-token','');
        if (empty($token)) return show([],0,'token错误');
        $url = env('curl.http', '0.0.0.0').RequestUrl::user_url();
        $data = Curl::post($url, ['token' => $token], ['x-csrf-token' => $token]);

        if ($data['code'] != 200) return show([],200,'token错误');
        self::$user = $data['data'];
        Lang::load(app()->getRootPath().'/app/lang/'.self::$user['language'].'.php');
        return $this;
    }

}